# Generated by Django 2.1.5 on 2019-01-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField(blank=True, null=True, verbose_name='Published Date1')),
                ('date2', models.DateField(blank=True, null=True, verbose_name='Published Date2')),
            ],
        ),
    ]
